### ISSUE TITLE
Reduce various wait times (especially after takeover game)

### ISSUE THREAD

**Issue by ReinhardPrix** [ReinhardPrix/FreedroidClassic#17]
Reminder to self before rolling out new Android release:
the 'forced' wait times in various places (especially after takeover game) can get annoying, and are not consistent with fast-paced expectations of modern times ;)

- takeover game
- after death, start new game

These should all be clickable-through to allow for a better experience for the impatient.

**Comment by matthiaskrgr** [comment]
I noticed this too, it might be good if the takeover game was speed up 2x or 3x after player and AI used all their codes.

Also, if the player destroyed all bots on a level, maybe allow them to move at 2x speed to find exists faster?

**Comment by ReinhardPrix** [comment]
mh, very nice ideas, I like it. I guess the empty-level speed-up wouldn't change the original game per se as long as energy also drains faster according to the time-speedup factor ( and this factor could be made configurable too, and set to 1.0 in 'strictly classic' setting).

**Comment by ReinhardPrix** [comment]
Closed by merge of PR #32
