### ISSUE TITLE
missing wav files for collisions

### ISSUE THREAD

**Issue by plawatsch** [ReinhardPrix/FreedroidClassic#35]
It seems that the rework of collision sounds did not include all relevant files.
Now in the source code some wav files are referenced (and used) that are not included in the sounds directory (Collision_Neutral.wav etc)

**Comment by plawatsch** [comment]
This seems to be the commit missing the new files:
https://github.com/ReinhardPrix/FreedroidClassic/commit/ae98e96e74f5ed73b77ad6116b0b5886fd5e36bf

**Comment by ReinhardPrix** [comment]
@plawatsch oops, thanks a lot for catching this. All missing files should now be committed ...

**Comment by plawatsch** [comment]
Issue is not really resolved since while the files have been added they have not been added to the make install target and they are thus not installed.

**Comment by ReinhardPrix** [comment]
ok 'make dist' now produces a working distribution file, but something seems weird with the data-path when doing 'make install', ... I'd need to look in that separately, see #36
