### ISSUE TITLE
Sound on collision with explosions is irritating and should be replaced with original sound

### ISSUE THREAD

**Issue by nuggetrix** [ReinhardPrix/FreedroidClassic#5]

**Comment by ReinhardPrix** [comment]
thanks for the feedback, that's the first time I hear a complaint about that sound. It is a bit metallic on purpose, I'll take your suggestion into consideration but I'm not sure if/when I would get around to replacing it.
If you have a better sound (that's free to use / GPL-compatible) then please let me know!

**Comment by ReinhardPrix** [comment]
sorry, but I'm afraid I don't have any time or plans at the moment to try and chase around for a different sound, and I'm actually quite liking it. However, suggestions are still welcome. (Remember, any suggested sound-files need to be compatible with GPL licence).

**Comment by ReinhardPrix** [comment]
actually, I did look into some sound improvements lately, and did fine a less annoying one, and more in line with the 'style' of the original game sounds.

**Comment by ReinhardPrix** [comment]
Related to #29
